apiVersion: v1
kind: Service
metadata:
  name: easy-game-server-svc 
  labels:
    environment: dev
    app: easy-game-server
    tier: frontend
spec:
  selector:
    app: easy-game-server
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  