apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: aj
    image: jonakola/random_num_1:1
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 10
      failureThreshold: 3
    ports:
    - name: http
      containerPort: 3000
