apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: aj
    image: jonakola/random_num_1:1
    volumeMounts:
    - name: game-config
      mountPath: /app/game_config
    resources:
      requests:
        cpu: '500m'
        memory: '128Mi'
      limits:
        cpu: '1000m'
        memory: '256Mi'
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 10
      failureThreshold: 3
    ports:
    - name: http
      containerPort: 3000
  volumes:
    - name: game-config
      configMap:
        name: game-config-file
